- name: remove all the node files
  file:
    path: "{{item}}"
    state: 'absent'
  with_items:
    - "{{ node_binary_directory }}/npm"
    - "{{ node_binary_directory }}/node"
    - "{{ node_binary_directory }}/npx"
    - "{{ node_binary_directory }}/node-gyp"
    - "{{ node_package_directory }}/node_modules"
    - "{{ node_prefix }}/include/node"
    - "{{ node_prefix }}/share/man/man1/node.1"
    - "{{ node_prefix }}/share/man/man1/npx.1"
    - "{{ node_prefix }}/share/man/man1/npm.1"
    - "{{ node_prefix }}/share/doc/node"
